name: Deploy AWS EKS

on:
  workflow_run:
    workflows: ['Release to Container Registry']
    types:
      - completed

concurrency:
  group: deploy_job
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: 4chain-ag/gateway-helm
          token: ${{ secrets.GH_TOKEN }}
          path: target-repo
 
      - name: Commit and push changes to helm repo
        run: |
            VERSION_NUMBER=$(git describe --tags `git rev-list --tags --max-count=1`)
            cd target-repo
            FILE_PATH="charts/gateway/charts/wallet-backend/Chart.yaml"
            sed -i 's/^appVersion: ".*"/appVersion: "'$VERSION_NUMBER'"/' $FILE_PATH
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "Wallet Web Backend Update $VERSION_NUMBER"
            git push origin main
