name: Release
permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: bactions/workflows/.github/workflows/release-go-server.yml@main
    with:
      version: ${{ github.ref_name }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.ON_RELEASE_SLACK_WEBHOOK_URL }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
